### ISSUE TITLE
Readme update Visually Appealing and Fostering Communication channels. 

### ISSUE THREAD

**Issue by Varunshiyam** [Avdhesh-Varshney/chanakya-niti-backend#17]
- To enhance communication and provide direct access to project guidance, I plan to include a dedicated Contact section. This section will feature the LinkedIn and GitHub profiles of each mentors and Admin enabling contributors to readily connect with them and address any project-related queries. 

- Additionally, to improve readability and organization, I Planned to implement clear visual separations between each section of the contributor documentation, ensuring a user-friendly and easily navigable experience.

- Finally, to foster a welcoming and inclusive environment, I will incorporate personalized welcome messages for our Repository.

- To effectively convey the essence of our project and its objectives, I propose creating a customized cover image for the repository. I believe a thoughtfully designed cover image can serve as a powerful communication tool

**Comment by Avdhesh-Varshney** [comment]
Not required.
