### ISSUE TITLE
User authentication system

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/chanakya-niti-backend#3]
- [ ] User sign/in or sign/up functionality
- [ ] proper routing 
- [ ] store the data in mongodb online server
- [ ] fetch it and logged the user and setting `logged in: true` 

**NOTE:** *URL of mongodb server is provided while creating the pr.*

**Comment by Madhavdua** [comment]
Kindly assign me this issue
Madhav dua
SSOC contributor

**Comment by Avdhesh-Varshney** [comment]
@Madhavdua go ahead.
