### ISSUE TITLE
Adding routes , controllers and middlewares to handle oauth

### ISSUE THREAD

**Issue by Edasgh** [Avdhesh-Varshney/chanakya-niti-backend#35]
Regarding the issue : https://github.com/Avdhesh-Varshney/chanakya-niti/issues/352

I want to add some routes, middlewares and controllers in "auth" to handle the login with oauth in the backend

@Avdhesh-Varshney  Please assign me this issue and add hacktoberfest label

**Comment by Avdhesh-Varshney** [comment]
Solve it before 5 pm

**Comment by Edasgh** [comment]
Ok

**Comment by Edasgh** [comment]
> Solve it before 5 pm

Not done yet...need more time....
